language: node_js
node_js:
- '4'
- '4.2'
- '4.1'
- '4.0'
- iojs
deploy:
  api_key:
    secure: oW2+UCaCz715ZguptuZLyTRND/RLMv2AOI+L8kPcPVrGex+Xpz3e9uNj3gyek3pRUTTb32OxEeRD6+Osh2R71rWrLkANKggXB1jAjI4WMCWDLdrDQ+hXbZ5utfGL/hVmJae/dDh4w4RsZCsdAzi6AW6tDSr8yJZG9F16lg+JkRgh9TgMkUl2IzCof96V7RRn0z08xo0D4pK3Mzk5S3VFyTjW6zs2gkVNPDBFOL7JO4j3IOrw8X5NiGDLqQ95/rJZODoEr9Fjwq2GITC4oyPhH/XS2OsjOdTaSEUdXnmQMI/sALBiwjKTzDm0WzspDGqXHzPkYYKytCCQk3NIfLmSVTbU75p7xOPVKyb8z1weoUo50ESc5u7vViubE1uV5iuNIPbCOOWCi+GCX20IluEW8MIzCEZvEIzFpPdtJf3QbLIEMeOTS2OqZv+vsX6Wf+rv2A/8Tfl4yfDYB1wly10UkMQGKQ+6LA7SPVuSb4bLwCSwtwH5MFSQKUwYZAp0RC8ljs7qvTdfgBh2CaCbS/jOg4tAWkGsfzP3wN4vVaYqQu9rCZQmmgf8Jba6iQyWRZaYGjLCAT35xu1kuoJOmxJykS0TLSdZVBjsbl9x2lRix7eAwp09SwZenTnCbOsM4cLM4aoW14cMzWdXm5GB6tK98rcOPj/jFIcjrUHMnZVxGUs=
  on: master
